FROM amazon/aws-lambda-python:3.8
ENV AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
ENV AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
RUN mkdir /app
WORKDIR /app
COPY requirements.txt ./
RUN pip install --target=. -r requirements.txt 
COPY ETLCovid19.py transformation.py import_csv.py ./
ENTRYPOINT [ "python" ]
CMD [ "-u", "ETLCovid19.py" ] 
