AWSTemplateFormatVersion: "2010-09-09"
Description: ACG ETLCovid19 CF Template
Resources:

#Import DynamoDB Table to store data
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        -
          AttributeName: "date"
          AttributeType: "S"
        -
          AttributeName: "cases"
          AttributeType: "S"
        - 
          AttributeName: "deaths"
          AttributeType: "S"
        - 
          AttributeName: "Recovered"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "date"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

#Import ETLCovid19 Lambda Function
  ETLCovid19Function:
    Type: AWS::Lambda::Function
    DeletionPolicy: Retain
    Properties:
      Handler: ETLCovid19.main
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: !Sub |
          var response = require('cfn-response');
          exports.handler = function(event, context) {
             var responseData = {Value: event.ResourceProperties.List};
             responseData.Value.push(event.ResourceProperties.AppendedItem);
             response.send(event, context, response.SUCCESS, responseData);
          };
      Runtime: python3.8

#Import ETLTriggerSNS Lambda Function
  ETLTriggerSNSFunction:
    Type: AWS::Lambda::Function
    DeletionPolicy: Retain
    Properties:
      Handler: trigger_sns.main
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: !Sub |
          var response = require('cfn-response');
          exports.handler = function(event, context) {
             var responseData = {Value: event.ResourceProperties.List};
             responseData.Value.push(event.ResourceProperties.AppendedItem);
             response.send(event, context, response.SUCCESS, responseData);
          };
      Runtime: python3.8

#Import SNS Topic for notification
  ETLCovid19Topic:
    Type: AWS::SNS::Topic
    DeletionPolicy: Retain
    Properties:
      Subscription:
        - Endpoint: "pif92@hotmail.com"
          Protocol: email

#Import SQS queue for retries
  ETLCovid19Queue:
  Type: AWS::SQS::Queue
  DeletionPolicy: Retain
  Properties:
    VisibilityTimeout: 30

#Import CloudWatch Log
