name: Copy CF file to S3 bucket
on: 
  push:
      branches: [ main ]
      paths:
        - 'backend/CloudFormation/**'
    
jobs:
  deploy_source:
    name: Copy file to S3
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - name: Upload package to S3 bucket
        uses: qoqa/action-s3-cp@v1.1
        env:
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_PATH: '/CloudFormation/ETLCovid19.yaml'
          FILE: './backend/CloudFormation/ETLCovid19.yaml'
