name: Test and Deploy to ACG_ETLCovid19 Function
on: 
  push:
      branches: [ main ]
      paths:
        - 'backend/ACGETLCovid19/**'
    
jobs:
  deploy_source:
    name: Test and Deploy to Lambda
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
        
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          
      - name: 'Test functions with Nose2'
        run: |
          pushd './backend/ACGETLCovid19/'
          yum install -y atlas-devel
          yum install -y atlas-sse3-devel 
          yum install -y blas-devel 
          yum install -y lapack-devel
          
          pip install awscli
          python -m pip install --upgrade pip
          pip install nose2
          pip install boto3
          pip install numpy
          pip install pandas   
          
          mkdir -p /home/runner/.local/lib/python3.8/site-packages
          
          cp /usr/lib64/atlas/* /home/runner/.local/lib/python3.8/site-packages
          cp /usr/lib64/libquadmath.so.0 /home/runner/.local/lib/python3.8/site-packages
          cp /usr/lib64/libgfortran.so.4 /home/runner/.local/lib/python3.8/site-packages
          
          python -m nose2 test_transformation.py
          
                
      - name: zip package
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./backend/ACGETLCovid19.zip ./backend/ACGETLCovid19
               
      - name: Deploy to Lambda
        uses: appleboy/lambda-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          function_name: ACG_ETLCovid19
          zip_file: backend/ACGETLCovid19.zip
