name: Test and Deploy to ACG_ETLCovid19 Function
on: 
  push:
      branches: [ main ]
      paths:
        - 'backend/ACGETLCovid19/**'
    
jobs:
  deploy_source:
    name: Test and Deploy to Lambda
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
        
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          
      - name: 'Test functions with Nose2'
        run: |
          pushd './backend/ACGETLCovid19/'
          cp home/runner/work/cloudguru-event-driven-python-aws/backend/ACGETLCovid19/numpy* /home/runner/.local/lib/python3.8/site-packages/
          cp home/runner/work/cloudguru-event-driven-python-aws/backend/ACGETLCovid19/pandas* /home/runner/.local/lib/python3.8/site-packages/
          cp home/runner/work/cloudguru-event-driven-python-aws/backend/ACGETLCovid19/dateutil* /home/runner/.local/lib/python3.8/site-packages/
          cp home/runner/work/cloudguru-event-driven-python-aws/backend/ACGETLCovid19/pytz* /home/runner/.local/lib/python3.8/site-packages/
          cp home/runner/work/cloudguru-event-driven-python-aws/backend/ACGETLCovid19/six* /home/runner/.local/lib/python3.8/site-packages/
          cp home/runner/work/cloudguru-event-driven-python-aws/backend/ACGETLCovid19/python_date* /home/runner/.local/lib/python3.8/site-packages/
          
          pip install awscli
          python -m pip install --upgrade pip
          pip install nose2
          pip install boto3    
          python -m nose2 test_transformation.py
          
                
      - name: zip package
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./backend/ACGETLCovid19.zip ./backend/ACGETLCovid19
               
      - name: Deploy to Lambda
        uses: appleboy/lambda-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          function_name: ACG_ETLCovid19
          zip_file: backend/ACGETLCovid19.zip
